@environment = http://localhost:8000

### GET Health Check

GET {{environment}}/health
Accept: application/json

### Request Prediction

POST {{environment}}/predict
Content-Type: application/json
Accept: application/json

{
  "source": "asda",
  "environment": "dev",
  "severity": "major",
  "metric_name": "service_unavailable",
  "ci": "server-test-01",
  "maintenance": "false"
}